const initialState = {
  heroes: [
    {
      id: '644',
      name: 'Superman',
      identity: 'Clark Kent',
      alignment: 'good',
      filiation: ['Justice League of America'],
      image: 'https://www.superherodb.com/pictures2/portraits/10/100/791.jpg',
      chart: {},
    },
    {
      id: '70',
      name: 'Batman',
      identity: 'Bruce Wayne',
      alignment: 'good',
      filiation: ['Justice League of America'],
      image: 'https://www.superherodb.com/pictures2/portraits/10/100/639.jpg',
      chart: {},
    },
    {
      id: '720',
      name: 'Wonder Woman',
      identity: 'Diana Prince',
      alignment: 'good',
      filiation: ['Justice League of America'],
      image: 'https://www.superherodb.com/pictures2/portraits/10/100/807.jpg',
      chart: {},
    },
  ],
  filter: {
    value: [0, 'Justice League of America'],
    type: [
      'filiation',
      'alignment',
      'name',
    ],
    filiation: [
      'Justice League',
      'Justice League of America',
      'Green Lantern Corps',
      'Flash Family',
      'Teen Titans',
      'Injustice League',
      'Justice League Dark',
      'Legion of Doom',
      'Suicide Squad',
      'Birds of Prey',
      'Justice Society of America',
      'Batman Family',
      'Outsiders',
      'Sinestro Corps',
      'Watchmen',
      'Young Justice',
      'League of Assassins',
      'Legion of Super-Heroes',
      'Justice League Unlimited',
      'Team Arrow',
      'Justice League International',
    ],
    alignment: [
      'good',
      'bad',
      'neutral',
    ],
  },
};

export default initialState;
